<?php

namespace AppBundle\Repository;

/**
 * ColocatairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColocatairesRepository extends \Doctrine\ORM\EntityRepository
{
}
