<?php

namespace AppBundle\Repository;

/**
 * ColocationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColocationsRepository extends \Doctrine\ORM\EntityRepository
{
}
